PAIRING_CODE_PREFIX = "FB"
PAIRING_CODE_SIZE = 4
PAIRING_TTL_MINUTES = 10

STATUS_PENDING_AUTH = "PENDING_AUTH"
STATUS_PENDING_AGENT = "PENDING_AGENT"
STATUS_AGENT_ONLINE = "AGENT_ONLINE"
STATUS_ACTIVE = "ACTIVE"
STATUS_CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED"
STATUS_EXPIRED = "EXPIRED"
STATUS_BLOCKED = "BLOCKED"
STATUS_DISABLED = "DISABLED"

ERROR_LOGIN_WALL = "LOGIN_WALL"
ERROR_CHECKPOINT = "CHECKPOINT"
ERROR_BLOCKED = "BLOCKED"
ERROR_NET = "NET"
ERROR_UNKNOWN = "UNKNOWN"

MARKETPLACE_URL = "https://www.facebook.com/marketplace/"
LOGIN_URL = "https://www.facebook.com/login"
